#!/bin/sh

# vet
go vet github.com/gabrielseibel1/gaef/auth/...
go vet github.com/gabrielseibel1/gaef/encounter/...
go vet github.com/gabrielseibel1/gaef/encounter-proposal/...
go vet github.com/gabrielseibel1/gaef/group/...
go vet github.com/gabrielseibel1/gaef/user/...
go vet github.com/gabrielseibel1/gaef/types/...
go vet github.com/gabrielseibel1/gaef/messenger/...
go vet github.com/gabrielseibel1/gaef/client/...

# unit tests
go test github.com/gabrielseibel1/gaef/auth/... --cover -count=1
go test github.com/gabrielseibel1/gaef/encounter/... --cover -count=1
go test github.com/gabrielseibel1/gaef/encounter-proposal/... --cover -count=1
go test github.com/gabrielseibel1/gaef/group/... --cover -count=1
go test github.com/gabrielseibel1/gaef/user/... --cover -count=1
go test github.com/gabrielseibel1/gaef/messenger/... --cover -count=1
go test github.com/gabrielseibel1/gaef/types/... --cover -count=1
