services:
  user-service:
    build:
        context: .
        dockerfile: user/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
  user-mongodb:
    image: mongo:6.0.4
    volumes:
      - user-mongodb-data:/data/db
  group-service:
    build:
      context: .
      dockerfile: group/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - GIN_MODE=release
  group-mongodb:
    image: mongo:6.0.4
    volumes:
      - group-mongodb-data:/data/db
  encounter-proposal-service:
    build:
      context: .
      dockerfile: encounter-proposal/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - GIN_MODE=release
  encounter-proposal-mongodb:
    image: mongo:6.0.4
    volumes:
      - encounter-proposal-mongodb-data:/data/db
  encounter-service:
    build:
      context: .
      dockerfile: encounter/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - GIN_MODE=release
  encounter-mongodb:
    image: mongo:6.0.4
    volumes:
      - encounter-mongodb-data:/data/db
volumes:
  user-mongodb-data:
  group-mongodb-data:
  encounter-proposal-mongodb-data:
  encounter-mongodb-data:
