services:
  user-service:
    build:
      context: ./user
      dockerfile: ./_debug/Dockerfile
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
      - "40000:40000"
  user-mongodb:
    image: mongo:6.0.4
    volumes:
      - user-mongodb-data:/data/db
  group-service:
    build:
      context: ./group
      dockerfile: ./_debug/Dockerfile
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "8081:8080"
      - "40001:40000"
  group-mongodb:
    image: mongo:6.0.4
    volumes:
      - group-mongodb-data:/data/db
volumes:
  user-mongodb-data:
  group-mongodb-data:
