services:
  user-service:
    build: ./user
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
  user-mongodb:
    image: mongo:6.0.4
    volumes:
      - user-mongodb-data:/data/db
  group-service:
    build: ./group
    ports:
      - "8081:8080"
    environment:
      - GIN_MODE=release
  group-mongodb:
    image: mongo:6.0.4
    volumes:
      - group-mongodb-data:/data/db
volumes:
  user-mongodb-data:
  group-mongodb-data:
