name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.4

      - name: Install dependencies
        run: go get .

      - name: Vet
        run: |
          go vet github.com/gabrielseibel1/gaef/auth/...
          go vet github.com/gabrielseibel1/gaef/encounter/...
          go vet github.com/gabrielseibel1/gaef/encounter-proposal/...
          go vet github.com/gabrielseibel1/gaef/group/...
          go vet github.com/gabrielseibel1/gaef/user/...

      - name: Test
        run: |
          go test github.com/gabrielseibel1/gaef/auth/... --cover -count=1
          go test github.com/gabrielseibel1/gaef/encounter/... --cover -count=1
          go test github.com/gabrielseibel1/gaef/encounter-proposal/... --cover -count=1
          go test github.com/gabrielseibel1/gaef/group/... --cover -count=1
          go test github.com/gabrielseibel1/gaef/user/... --cover -count=1

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json
